services:
#    user.example:
#        class: LFP\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    # Fixtures services
    LFP\UserBundle\DataFixtures\ORM\LoadUser:
        tags: [doctrine.fixture.orm]
